### ISSUE TITLE
Tidy up upgrade documetation

### ISSUE THREAD

**Issue by thelem** [FriendsOfSymfony/FOSCKEditorBundle#170]
I've been left scratching my head after the module totally stopped working after upgrading from 1.x to 2.x. There were no error messages to help me and I couldn't find any upgrade instructions.

I eventually found useful upgrade documentation in UPGRADE-2.0.md

**Changes required**

1. UPGRADE-2.x.md is basically an empty stub. It should be deleted.
2. CHANGELOG.md in the 2.x branch says the latest release was 1.1.0. Newer versions should be added.
3. Official docs at https://symfony.com/doc/master/bundles/FOSCKEditorBundle/index.html tell you how to migrate from Ivory, but not how to migrate from 1.0 to 2.0. They should either reference UPGRADE-2.0.md, or link to it.

**Comment by kunicmarko20** [comment]
1. UPGRADE-2.x.md is basically an empty stub. It should be deleted.

Reason for this is because there we will have new changes here for 2.x version

2. CHANGELOG.md in the 2.x branch says the latest release was 1.1.0. Newer versions should be added.

Yep, my fault.

3. Official docs at https://symfony.com/doc/master/bundles/FOSCKEditorBundle/index.html tell you how to migrate from Ivory, but not how to migrate from 1.0 to 2.0. They should either reference UPGRADE-2.0.md, or link to it.

You can always check the release notes.
