### ISSUE TITLE
(Re-) enable travis as CI

### ISSUE THREAD

**Issue by ElectricMaxxx** [FriendsOfSymfony/FOSCKEditorBundle#4]

**Comment by fbourigault** [comment]
What about moving to what is recommended in Symfony documentation ? https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration

**Comment by stof** [comment]
the config should indeed be cleaned:

- not requiring a Symfony version for each job (and using the locking package for jobs testing a specific versions rather than changing requirements)
- I suggest using separate commands in the travis.yml rather than an external script, as this allows seeing the different commands in the Travis logs
- drop the docker-based job (not worth running docker inside the Travis container IMO)

**Comment by stof** [comment]
We should also enable the appveyor build as we have the config for it

**Comment by ElectricMaxxx** [comment]
completely :+1: i really like the config proposed in best practices. And i really like the script idea, as i can reuse those scripts locally to get a specific setup.

**Comment by stof** [comment]
I'm suggesting *not* using them anymore (they are quite unlikely to be usable locally anyway)

**Comment by ElectricMaxxx** [comment]
We should'nt have that much of commands to execute, so i can go with it. We can discuss scripts or not on an other issue/meeting/conference :-).
